before_install: gem install bundler --pre
before_script: bundle exec rake db:migrate
bundler_args: --without assets:development:production
language: ruby
rvm:
  - 1.9.3

notifications:
  irc:
    channels:
      - 'irc.freenode.org:6667#codeforamerica'
